### ISSUE TITLE
Chapter 6 examples have core_version_requirement: '>=9'

### ISSUE THREAD

**Issue by Cleets** [PacktPublishing/Drupal-10-Development-Cookbook#11]
shouldn't modules' mymodule.yml.info files include  
core_version_requirement: '>=9 || >=10'

**Comment by gitressa** [comment]
`core_version_requirement: '>=9'` is the correct format, since it means 9 and every version above:

> To define a module as compatible with all versions of core from 8.7.7 onwards, you may use the notation ">=8". If your module is unaffected by Drupal 8 or Drupal 9 deprecations, this will allow it to continue to be installed on Drupal 10 and later releases without having to update the .info.yml each time.

```
name: My Module
type: module
core_version_requirement: ">=8"
```

From [New 'core_version_requirement' key in info.yml files for modules, themes and profiles allows Composer semantic version constraints including specifying multiple major versions of core](https://www.drupal.org/node/3070687).
